PruebaTest/Models/Mensajes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public int IdMensaje { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}

PruebaTest/Controllers/MensajeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PruebaTest.Models;

namespace PruebaTest.Controllers
{
    public class MensajeController : Controller
    {
        public void listarUsuarios()
        {
            List<SelectListItem> listar;
            using(var bd=new BDPruebaTecnicaEntities())
            {
                listar = (from item in bd.Usuarios
                          where item.Habilitado == 1
                          select new SelectListItem
                          {
                              Text = item.Nombre,
                              Value = item.IdUsuario.ToString()
                          }).ToList();

                listar.Insert(0, new SelectListItem { Text = " - Seleccionar -", Value = "" });
                ViewBag.listarUsuarios = listar;
            }
        }
        // GET: Mensaje
        public ActionResult Index()
        {
            listarUsuarios();
            List<MensajeCLS> lista = null;
            using(var bd=new BDPruebaTecnicaEntities())
            {
                lista = (from tablaM in bd.Mensajes
                         //se realiza un join para traer la info de la otra tabla (tablaUsuario)
                         join tablaUsuario in bd.Usuarios
                         on tablaM.IdUsuario equals tablaUsuario.IdUsuario
                         where tablaM.Habilitado == 1
                         select new MensajeCLS
                         {
                             idMensaje = tablaM.IdMensaje,
                             mensaje = tablaM.Mensaje,
                             fechaPublicacion = (DateTime)tablaM.Fecha,
                             nombreU = tablaUsuario.Nombre
                         }).ToList();
            }
            return View(lista);
        }

        public ActionResult Agregar()
        {
            listarUsuarios();
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(MensajeCLS oMensajeCls)
        {
            if (!ModelState.IsValid)
            {
                listarUsuarios();
                return View(oMensajeCls);
            }
            else
            {
                using (var bd = new BDPruebaTecnicaEntities())
                {
                    Mensajes oMensaje = new Mensajes();
                    oMensaje.Mensaje = oMensajeCls.mensaje;
                    oMensaje.Fecha = oMensajeCls.fechaPublicacion;
                    oMensaje.IdUsuario = oMensajeCls.idUsuarioM;
                    oMensaje.Habilitado = 1;
                    bd.Mensajes.Add(oMensaje);
                    bd.SaveChanges();
                }
            }

            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            listarUsuarios();
            MensajeCLS oMensajeCls = new MensajeCLS();
            using(var bd = new BDPruebaTecnicaEntities())
            {
                Mensajes oMensaje = bd.Mensajes.Where(vr => vr.IdMensaje.Equals(id)).First();
                oMensajeCls.idMensaje = oMensaje.IdMensaje;
                oMensajeCls.mensaje = oMensaje.Mensaje;
                oMensajeCls.fechaPublicacion = (DateTime)oMensaje.Fecha;
                oMensajeCls.idUsuarioM = (int)oMensaje.IdUsuario;
            }

            return View(oMensajeCls);
        }

        [HttpPost]
        public ActionResult Editar(MensajeCLS oMensajeCls)
        {
            if (!ModelState.IsValid)
            {
                listarUsuarios();
                return View(oMensajeCls);
            }
            else
            {
                listarUsuarios();
                int idMen = oMensajeCls.idMensaje;
                using(var bd=new BDPruebaTecnicaEntities())
                {
                    Mensajes oMensaje = bd.Mensajes.Where(vr => vr.IdMensaje.Equals(idMen)).First();
                    oMensaje.Mensaje = oMensajeCls.mensaje;
                    oMensaje.Fecha = oMensajeCls.fechaPublicacion;
                    oMensaje.IdUsuario = oMensajeCls.idUsuarioM;
                    bd.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Eliminar(int idMensaje)
        {
            using (var bd=new BDPruebaTecnicaEntities())
            {
                Mensajes oMensaje = bd.Mensajes.Where(vr => vr.IdMensaje.Equals(idMensaje)).First();
                oMensaje.Habilitado = 0;
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

PruebaTest/Views/Mensaje/Agregar.cshtml
@using PruebaTest.Models
@model MensajeCLS
@{
    ViewBag.Title = "Agregar";

    List<SelectListItem> listarUsuarios = (List<SelectListItem>)ViewBag.listarUsuarios;
}

<h2>Agregar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Mensaje", FormMethod.Post))
        {
        <div>
            @Html.Label("Mensaje")
            @Html.TextArea("mensaje", null, new { @class="form-control", @placeholder="Escriba su mensaje"})
            @Html.ValidationMessage("mensaje", new { @class="text-danger"})
        </div>
        <div>
            @Html.Label("Fecha de publicación")
            @Html.TextBox("fechaPublicacion", null, new { @class="form-control", @type="date"})
            @Html.ValidationMessage("fechaPublicacion", new { @class="text-danger"})
        </div>
        <div>
            @Html.Label("Usuario que publicara")
            @Html.DropDownList("idUsuarioM", listarUsuarios, null, new { @class = "form-control" })
            @Html.ValidationMessage("idUsuarioM", new { @class = "text-danger" })
        </div>
        <br />
        <div style="margin:auto">
            <input type="submit" class="btn btn-success" value="Guardar"/>
        </div>
        }
    </div>
</div>

PruebaTest/Views/Mensaje/Editar.cshtml
@using PruebaTest.Models
@model MensajeCLS
@{
    ViewBag.Title = "Editar";
    List<SelectListItem> listarUsuarios = (List<SelectListItem>)ViewBag.listarUsuarios;
}

<h2>Editar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Editar", "Mensaje", FormMethod.Post))
        {
            //Para ocultar un campo debe ubicarse dentro de la etiqueta el codigo(style="display:none")
            <div style="display:none">
                @Html.Label("Id del mensaje")
                @Html.TextBox("idMensaje", null, new { @class="form-control", @readonly=true})
            </div>
            <div>
                @Html.Label("Mensase publicado")
                @Html.TextArea("mensaje", null, new { @class="form-control"})
                @Html.ValidationMessage("mensaje", new { @class="text-danger"})
            </div>
            <div>
                @Html.Label("Fecha de la publicación")
                @Html.EditorFor(vr => vr.fechaPublicacion, null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("fechaPublicacion", new { @class="text-danger"})
            </div>
            <div>
                @Html.Label("Usuario que realizo la publicación")
                @Html.DropDownList("idUsuarioM", listarUsuarios, null, new { @class="form-control"})
                @Html.ValidationMessage("idUsuarioM", new { @class="text-danger"})
            </div>
            <br />
            <div style="margin:auto">
                @Html.ActionLink("Regresar", "Index", "Mensaje", new { @class="btn btn-secondary"})
                <input type="submit" class="btn btn-success" value="Guardar"/>
            </div>
        }
    </div>
</div>

PruebaTest/Views/Mensaje/Index.cshtml
@using PruebaTest.Models
@model List<MensajeCLS>

@{
    ViewBag.Title = "Index";

    //List<SelectListItem> listarUsuarios = (List<SelectListItem>)ViewBag.listarUsuarios;
}

<h2>Index</h2>

@Html.ActionLink(" ", "Agregar", "Mensaje", new { @class = "fas fa-user-plus fa-2x btn btn-primary" })

<br />
<br />
<div class="row">
    <table class="table table-bordered table-hover">
        <thead class="text-center">
            <tr>
                <td>Id del Mensaje</td>
                <td>Mensaje</td>
                <td>Fecha de publicación</td>
                <td>Usuario</td>
                <td>Operaciones</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">@item.idMensaje</td>
                    <td>@item.mensaje</td>
                    <td class="text-center">@item.fechaPublicacion.ToString("dd/MM/yyyy")</td>
                    <td class="text-center">@item.nombreU</td>
                    <td>
                        @Html.ActionLink(" ", "Editar", "Mensaje", new { id = @item.idMensaje }, new { @class = "fas fa-user-edit btn btn-primary" })
                        @*@Html.ActionLink(" ", "Eliminar", "Mensaje", new { id = @item.idMensaje }, new { @class = "far fa-trash-alt btn btn-danger" })*@

                        <!-- Button trigger modal -->
                        <button type="button" onclick="mostrarPopup(@item.idMensaje)" class="far fa-trash-alt btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @using(Html.BeginForm("Eliminar", "Mensaje", FormMethod.Post, new { @id = "frmEliminar" }))
    {
        @Html.Hidden("idMensaje")
    }

</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            
            <div class="modal-body">
                ¿Esta seguro de eliminar el mensaje?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="button" onclick="Eliminar()" class="btn btn-danger">Aceptar</button>
            </div>
        </div>
    </div>
</div>

<script>
    function mostrarPopup(idMensaje) {
        document.getElementById("idMensaje").value = idMensaje;
    }
    function Eliminar() {
        var frmEliminando = document.getElementById("frmEliminar");
        frmEliminando.submit();
    }
</script>